### ISSUE TITLE
How to open this on Blender?

### ISSUE THREAD

**Issue by dlight** [mixandjam/Jammo-Character#1]
Hello, I can only find `*.asset` files on this repository. But Blender can't open or import it.

Is there a `*.blend` file somewhere?

**Comment by mixandjam** [comment]
> Hello, I can only find `*.asset` files on this repository. But Blender can't open or import it.
> 
> Is there a `*.blend` file somewhere?

The link for the original .blend files is this one:
http://bit.ly/jammoDB
Since there might be updates on the original files by Curiomatic - I imagined it would be easier to keep it separate from the repository.

Adding the link to the readme! Thanks for the heads up!
